"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------- Security ------------------------------------------------- #

# Fail loud if SECRET_KEY is not set
SECRET_KEY = os.environ['SECRET_KEY']

# Fail loud if DEBUG is not explicitly set
_debug = os.environ.get('DEBUG')
if _debug is None:
    raise ValueError('DEBUG must be explicitly set in environment (true/false)')
DEBUG = _debug.lower() == 'true'

ALLOWED_HOSTS = [
    'unhinged-lander.localhost',  # remapped for nginx (dev)
    'localhost',
    '127.0.0.1',
    'nhinged.io',                 # production
    'www.nhinged.io',
]

CSRF_TRUSTED_ORIGINS = [
    'https://unhinged-lander.localhost',
    'https://nhinged.io',
    'https://www.nhinged.io',
]


# ---------------- Application definition --------------------------------------- #

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # project apps
    'lander',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'middleware.wide_event_logging.WideEventLoggingMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'config.context_processors.goatcounter_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.unhinged_lander'


# ---------------- Database -------------------------------------------------- #

DATABASES = {
    'default': dj_database_url.config(
        default=f'postgresql://{os.getenv("PG_USER")}:{os.getenv("PG_PASS")}@{os.getenv("PG_HOST")}:{os.getenv("PG_PORT")}/{os.getenv("PG_DATABASE")}',
        conn_max_age=600,
    )
}


# ---------------- Password validation --------------------------------------- #

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ---------------- Internationalization -------------------------------------- #

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------- Static files ---------------------------------------------- #

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------- Logging -------------------------------------------------- #

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'wide_event': {
            'format': '%(message)s',
        },
    },
    'handlers': {
        'wide_event_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'wide_event',
        },
    },
    'loggers': {
        'wide_event': {
            'handlers': ['wide_event_console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
